### ISSUE TITLE
Inversion fails when adding a prompt

### ISSUE THREAD

**Issue by daiqing-qi** [QianWangX/MDP-Diffusion#4]
Thanks for sharing the code! It works well with an empty prompt during the null-text inversion, however, when I add a prompt that describes the input image (which is supprted by null-text inversion paper), the generated image will be totally unrelated to the input image.

May I ask the potential causes of the problem? (Note that I got a  WARNING: `steps_offset` should be set to 1 instead of 0, I am not sure if it can affect the model)

Many thanks!

**Comment by QianWangX** [comment]
Hi @daiqing-qi , thanks for your comments! I already updated the notebook, it was because I didn't use the `prompt` variable in the next line. 

I think the second issue is because of different versions of the diffusers library. Did you check that you are using the same diffusers version as in the code?

**Comment by daiqing-qi** [comment]
> 

Thanks for your reply! The second issue can just be ignored. 

BTW, have you treid to use prediction_type='v_prediction' for the DDIMScheduler? I find the inversion fails if it is set so.

**Comment by daiqing-qi** [comment]
> Hi @daiqing-qi , thanks for your comments! I already updated the notebook, it was because I didn't use the `prompt` variable in the next line.
> 
> I think the second issue is because of different versions of the diffusers library. Did you check that you are using the same diffusers version as in the code?

Hi @QianWangX , Thanks for your reply! The second issue can just be ignored.

BTW, have you treid to use prediction_type='v_prediction' for the DDIMScheduler? I find the inversion fails if it is set so.

**Comment by QianWangX** [comment]
Hi @daiqing-qi , sorry for the late reply. I think 'v_prediction' refers to the v_prediction parameterization proposed in the paper "Progressive Distillation for Fast Sampling of Diffusion Models" [[paper](https://arxiv.org/pdf/2202.00512.pdf)]. The models predicts "v" if you use 'v_prediction'. However I think in the Null Text Inversion paper (the inversion method I use in this codebase), the model predict the epsilon.
